### PR TITLE
cmake install fix

### PR DESCRIPTION
**Pull request by tylerjw**
I needed this change to make a from source build of ros2 work where I was depending on this package.

### CODE REVIEW

**Review by Abishalini — APPROVED** [review]
I tested this on my end and it fixed my source build

**Comment by Ace314159** [comment]
@tylerjw @wxmerkt  This change broke my build of MoveIt2 Foxy. Can a foxy branch be created to preserve the old behavior?

**Comment by wxmerkt** [comment]
@Ace314159 I pushed a `foxy` branch without the change

**Comment by Ryanf55** [comment]
Can the maintainers release to rolling? It's causing failures in our CI here:
https://github.com/ANYbotics/grid_map/pull/483#issuecomment-2464124564

**Comment by wxmerkt** [comment]
Thank you for the ping @Ryanf55. Release ongoing, will update #22 once done

**Pull request merged**
