### PR TITLE
Porting to ROS2

### PR DESCRIPTION
**Pull request by anasarrak**
Can we create a ros2 branch to allocate these changes?

### CODE REVIEW

**Comment by ahornung** [comment]
I created a new ros2 branch, would you mind changing the PR to that one?

**Comment by wxmerkt** [comment]
@ahornung I just changed the target branch

@anasarrak Would it be possible to squash the changes down to a few meaningful ones - e.g., change-to-C++-14, change-to-amend-and-update-package-format, etc.?

Background: The changes to the msg and conversions-header files are good fixes and could also be added to the ROS1 version.

**Comment by anasarrak** [comment]
@wxmerkt I've made the requested changes, I don't know if it's what you are looking for, if you need any other change let me know.

**Comment by anasarrak** [comment]
@ahornung can we merge this?

**Comment by wxmerkt** [comment]
Can you please also cherry-pick and PR the conversions.h updates and message fixes to the ROS1 branch, then we can rebase the ros2 branch off that master - making the changes more minimal. Can you also please revert the change to README? Thank you :-)

**Comment by anasarrak** [comment]
@wxmerkt The only changes that can be applied on melodic, are the ones that are on the ``.msg`` and the changes on the headers from ``Octomap& msg`` to ``Octomap& octomap_msgs::msg``, am I right?

**Comment by wxmerkt** [comment]
I thought so - but haven't tested.

**Comment by wxmerkt** [comment]
Superseded by #13

**Pull request closed without merging**
